jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: zendesk/checkout@v2
      with:
        fetch-depth: '1'
    - continue-on-error: true
      name: Set up QEMU
      run: 'QEMU_IMAGE=tonistiigi/binfmt:latest

        docker pull $QEMU_IMAGE

        docker image inspect $QEMU_IMAGE

        docker run --rm --privileged $QEMU_IMAGE --install all'
    - continue-on-error: true
      id: buildx
      name: Set up Docker Buildx
      uses: zendesk/setup-buildx-action@v1.6.0
      with:
        install: true
    - continue-on-error: true
      name: Docker Build and push
      run: 'set -eu -o pipefail

        echo ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }} | docker login --username=${{
        secrets.DOCKER_HUB_USERNAME }} --password-stdin

        set -x

        current_tag=zendesk/maxwell:"${GITHUB_REF##refs/tags/}"

        latest_tag=zendesk/maxwell:latest

        docker buildx build --platform=linux/arm64,linux/amd64 --file=Dockerfile --push
        --tag="$current_tag" --tag="$latest_tag" .'
name: CI to Zendesk Dockerhub
on:
  repository_dispatch:
    types: trigger-ga___ci.yaml
